name: krunner
description: A user-friendly API for KDE's KRunner application.
version: 0.1.0
repository: https://github.com/Merrit/krunner-dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dbus: ^0.6.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
