name: krunner
version: 1.0.2
description: A user-friendly API for KDE's KRunner application. Provides a simple and reliable way to write krunner plugins, also known  as "runners".
repository: https://github.com/Merrit/krunner-dart

platforms:
  linux:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dbus: ^0.7.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
